import { ChangeDetectionStrategy, Component, input } from '@angular/core'
import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconAward,
  IconBell,
  IconBrandBluesky,
  IconBrandMastodon,
  IconBrandX,
  IconBroadcast,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCloudDownload,
  IconCloudOff,
  IconCode,
  IconCoinYuan,
  IconColumns,
  IconCopy,
  IconDeviceGamepad2,
  IconDownload,
  IconEdit,
  IconEye,
  IconEyeOff,
  IconExternalLink,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFlame,
  IconGripHorizontal,
  IconHelpCircle,
  IconHistory,
  IconHome,
  IconKeyboard,
  IconLayoutDashboard,
  IconLanguage,
  IconLink,
  IconList,
  IconLoader,
  IconLogin,
  IconLogout,
  IconMaximize,
  IconMenu2,
  IconMessage,
  IconMessageCircle,
  IconMinimize,
  IconMoodSmile,
  IconPlayerPlay,
  IconPlaylist,
  IconPlus,
  IconRefresh,
  IconRepeat,
  IconRobot,
  IconSearch,
  IconSend,
  IconSettings,
  IconShare,
  IconShield,
  IconStar,
  IconTag,
  IconThumbDown,
  IconThumbUp,
  IconTrash,
  IconTrendingUp,
  IconUpload,
  IconUser,
  IconUserMinus,
  IconUserPlus,
  IconUsers,
  IconVideo,
  IconVolume,
  IconWorld,
  IconX,
  IconDots,
  IconDotsVertical,
  TablerIconComponent,
  type TablerIcon
} from '@tabler/icons-angular'

const icons = {
  // GameHub uses one outline icon family for every shared icon entry. Keep the
  // public names stable because PeerTube templates and plugins use them.
  'markdown': IconFileText,
  'language': IconLanguage,
  'video-lang': IconLanguage,
  'support': IconHelpCircle,
  'peertube-x': IconBrandX,
  'robot': IconRobot,
  'playlist-add': IconPlaylist,
  'follower': IconUserMinus,
  'following': IconUserPlus,
  'tip': IconCoinYuan,
  'flame': IconFlame,
  'fediverse': IconWorld,
  'mastodon': IconBrandMastodon,
  'x-twitter': IconBrandX,
  'bluesky': IconBrandBluesky,
  'menu': IconMenu2,
  'link': IconLink,
  'history': IconHistory,
  'registry': IconList,
  'subscriptions': IconBell,
  'videos': IconVideo,
  'add': IconPlus,
  'plus': IconPlus,
  'alert': IconAlertTriangle,
  'alert-circle': IconAlertCircle,
  'circle-alert': IconAlertCircle,
  'chapters': IconList,
  'studio': IconLayoutDashboard,
  'overview': IconLayoutDashboard,
  'moderation': IconShield,
  'captions': IconMessage,
  'config': IconSettings,
  'cog': IconSettings,
  'award': IconAward,
  'bell': IconBell,
  'opened-bell': IconBell,
  'channel': IconVideo,
  'chevrons-up': IconChevronUp,
  'chevron-up': IconChevronUp,
  'chevron-down': IconChevronDown,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'coin': IconCoinYuan,
  'arrow-left': IconArrowLeft,
  'arrow-down': IconArrowDown,
  'arrow-up': IconArrowUp,
  'circle-tick': IconCircleCheck,
  'clock-arrow-down': IconClock,
  'clock': IconClock,
  'cloud-download': IconCloudDownload,
  'cloud-error': IconCloudOff,
  'codesandbox': IconCode,
  'columns': IconColumns,
  'keyboard': IconKeyboard,
  'copy': IconCopy,
  'cross': IconX,
  'delete': IconTrash,
  'dislike': IconThumbDown,
  'download': IconDownload,
  'edit': IconEdit,
  'eye': IconEye,
  'exit-fullscreen': IconMinimize,
  'external-link': IconExternalLink,
  'eye-close': IconEyeOff,
  'eye-open': IconEye,
  'film': IconVideo,
  'filter': IconFilter,
  'flag': IconFlag,
  'fullscreen': IconMaximize,
  'globe': IconWorld,
  'help': IconHelpCircle,
  'home': IconHome,
  'like': IconThumbUp,
  'thumbs-up': IconThumbUp,
  'live': IconBroadcast,
  'message-circle': IconMessageCircle,
  'more-horizontal': IconDots,
  'more-vertical': IconDotsVertical,
  'move-right': IconArrowRight,
  'no': IconCircleX,
  'ownership-change': IconShare,
  'p2p': IconBroadcast,
  'play': IconPlayerPlay,
  'playlists': IconPlaylist,
  'refresh': IconRefresh,
  'refresh-cw': IconRefresh,
  'loader': IconLoader,
  'repeat': IconRepeat,
  'search': IconSearch,
  'share': IconShare,
  'star': IconStar,
  'tag': IconTag,
  'shield': IconShield,
  'sign-in': IconLogin,
  'sign-out': IconLogout,
  'stats': IconChartBar,
  'syndication': IconShare,
  'tick': IconCheck,
  'trending': IconTrendingUp,
  'undo': IconArrowBackUp,
  'upload': IconUpload,
  'volume-2': IconVolume,
  'user-add': IconUserPlus,
  'user-x': IconUserMinus,
  'user': IconUser,
  'grip-horizontal': IconGripHorizontal,
  'gamepad': IconDeviceGamepad2,
  'calendar': IconCalendar,
  'users': IconUsers,
  'mood-smile': IconMoodSmile,
  'send': IconSend
} satisfies Record<string, TablerIcon>

export type GlobalIconName = keyof typeof icons

@Component({
  selector: 'my-global-icon',
  template: '<tabler-icon [icon]="icons[iconName()]" [size]="24" [stroke]="2" />',
  styleUrls: [ './common-icon.component.scss' ],
  imports: [ TablerIconComponent ],
  host: { 'aria-hidden': 'true' },
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true
})
export class GlobalIconComponent {
  protected readonly icons = icons
  readonly iconName = input.required<GlobalIconName>()
}
